# Site settings
title: Bitwise South Stadium 360 Tour
email: csaba.toth.us@gmail.com
description: 360 views inside of Bitwise South Stadium.
baseurl: "/BWSS360tour" # the subpath of your site, e.g. /blog/
url: "http://gdgfresno.github.io" # the base hostname & protocol for your site
copyright: '&copy; 2016 ValleyDevFest'

# Links
devfest: "https://valleydevfest.com"
bitwise: "http://bitwiseindustries.com"

# Build settings
markdown: kramdown

# Custom theme could be generated at: https://getmdl.io/customize/index.html
material_theme: blue-deep_orange

# Google Analytics account ID (UA-XXXXXXXX-X)

google-analytics-ua: UA-84006029-2
